#!/usr/bin/env python3
"""Generate skills/INDEX.md from SKILL.md frontmatter."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
INDEX_PATH = SKILLS_DIR / "INDEX.md"


def parse_frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    frontmatter: list[str] = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        frontmatter.append(line)

    data: dict[str, str] = {}
    i = 0
    while i < len(frontmatter):
        line = frontmatter[i]
        if ":" not in line:
            i += 1
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value in {">", "|"}:
            block: list[str] = []
            i += 1
            while i < len(frontmatter):
                candidate = frontmatter[i]
                if candidate and not candidate.startswith((" ", "\t")) and ":" in candidate:
                    break
                block.append(candidate.strip())
                i += 1
            data[key] = " ".join(part for part in block if part)
            continue
        data[key] = value.strip("'\"")
        i += 1
    return data


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def main() -> None:
    rows: list[tuple[str, str, Path, Path]] = []
    for skill_file in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        meta = parse_frontmatter(skill_file)
        name = meta.get("name") or skill_file.parent.name
        description = meta.get("description") or "(no description)"
        rows.append((name, description, skill_file.relative_to(ROOT), skill_file.relative_to(SKILLS_DIR)))

    lines = [
        "# Skill Index",
        "",
        "<!-- AUTO-GENERATED by tools/generate_skill_index.py. Do not edit by hand. -->",
        "",
        "This index is generated from the frontmatter in each `skills/*/SKILL.md` file.",
        "Run `tools/.venv/bin/python tools/generate_skill_index.py` after adding, removing, or renaming a skill.",
        "",
        "| Skill | Path | Description |",
        "|---|---|---|",
    ]
    for name, description, display_path, link_path in rows:
        lines.append(
            f"| `{markdown_escape(name)}` | [{display_path.as_posix()}]({link_path.as_posix()}) | {markdown_escape(description)} |"
        )
    lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
