#!/usr/bin/env python3
"""Merge per-bot session logs into the canonical session.md (LSM-style compaction).

Each participant appends only to their own ``session.<bot>.md`` file — their
private "memtable". This script is the compaction step: it reads every
``session.*.md`` in a session directory, parses the timestamped entries, and
merges them into a single chronologically-ordered ``session.md``. Because no two
agents ever write the same file, there are no write-races to coordinate around.

Entry format (in each ``session.<bot>.md``)::

    ## [<handle>, <ISO-8601 timestamp>]
    ...body...

    **→ Handoff:** ...        # optional

The header line is the merge key. Timestamps may carry a timezone offset
(RFC 3339, e.g. ``2026-06-08T07:58:00+02:00``); they are normalized to UTC before
sorting, so agents in different timezones interleave correctly. Naive timestamps
(no offset) are assumed to be UTC. Ties break by
(utc-instant, source-file, original-order) so the merge is deterministic.
Unparseable timestamps sort last, preserving their raw string order.

``session.md`` is GENERATED — never hand-edit it. During an active collaboration
session, agents should watch each other's ``session.<bot>.md`` files directly
with git, tail, editor refresh, or collab MCP messages. Run this script once at
session closeout, or when a pre-commit ``--check`` reports that ``session.md`` is
stale.

Usage::

    tools/merge_sessions.py doc/collab/sessions/<YYYY-MM-DD-slug>/  # final compaction
    tools/merge_sessions.py <dir> --check     # exit 1 if session.md is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Sentinel UTC instant for unparseable timestamps: sort them after everything.
_FAR_FUTURE = datetime.max.replace(tzinfo=timezone.utc)


def to_utc(ts: str) -> datetime:
    """Normalize an ISO-8601 / RFC-3339 timestamp to a UTC instant for sorting.

    Accepts trailing ``Z``; assumes UTC for naive timestamps.
    Returns a far-future sentinel for unparseable input so it sorts last.
    """
    try:
        dt = datetime.fromisoformat(ts.strip().replace("Z", "+00:00"))
    except ValueError:
        return _FAR_FUTURE
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)

HEADER_RE = re.compile(r"^##\s*\[\s*([^,\]]+?)\s*,\s*([^\]]+?)\s*\]\s*$")
GENERATED_BANNER = "<!-- GENERATED by tools/merge_sessions.py - DO NOT EDIT. Edit session.<bot>.md instead. -->"
NON_PARTICIPANT_HANDLES = {"closed"}


@dataclass
class Entry:
    handle: str
    timestamp: str
    body: str
    source: str
    order: int = field(default=0)

    @property
    def sort_key(self) -> tuple:
        # Normalize to a UTC instant so cross-timezone entries interleave
        # correctly; tie-break on source file then original order for stability.
        return (to_utc(self.timestamp), self.source, self.order)

    def render(self) -> str:
        out = f"## [{self.handle}, {self.timestamp}]\n{self.body.rstrip()}\n"
        return out


def parse_entries(path: Path) -> list[Entry]:
    """Split a per-bot file into entries keyed by ``## [handle, timestamp]`` headers."""
    text = path.read_text()
    entries: list[Entry] = []
    current: Entry | None = None
    buf: list[str] = []
    order = 0
    for line in text.splitlines():
        m = HEADER_RE.match(line)
        if m:
            if current is not None:
                current.body = "\n".join(buf).strip("\n")
                entries.append(current)
            current = Entry(
                handle=m.group(1).strip(),
                timestamp=m.group(2).strip(),
                body="",
                source=path.name,
                order=order,
            )
            order += 1
            buf = []
        elif current is not None:
            buf.append(line)
        # lines before the first header (frontmatter / notes) are ignored
    if current is not None:
        current.body = "\n".join(buf).strip("\n")
        entries.append(current)
    return entries


def collect(session_dir: Path) -> list[Entry]:
    entries: list[Entry] = []
    for path in sorted(session_dir.glob("session.*.md")):
        if path.name == "session.md":  # defensive; glob won't match this anyway
            continue
        entries.extend(parse_entries(path))
    return entries


def render_session(session_dir: Path, entries: list[Entry]) -> str:
    ordered = sorted(entries, key=lambda e: e.sort_key)
    participants = sorted(
        {e.handle for e in entries if e.handle.lower() not in NON_PARTICIPANT_HANDLES},
        key=str.lower,
    )
    slug = session_dir.name
    lines = [
        GENERATED_BANNER,
        "",
        f"# Session: {slug}",
        "",
        "## Participants",
        "",
    ]
    lines += [f"- {p}" for p in participants]
    lines += ["", "---", ""]
    lines += [e.render() for e in ordered]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("session_dir", type=Path)
    ap.add_argument("--check", action="store_true", help="exit 1 if session.md is stale (do not write)")
    args = ap.parse_args(argv)

    session_dir: Path = args.session_dir
    if not session_dir.is_dir():
        print(f"error: not a directory: {session_dir}", file=sys.stderr)
        return 2

    entries = collect(session_dir)
    if not entries:
        print(f"warning: no entries found in session.*.md under {session_dir}", file=sys.stderr)

    rendered = render_session(session_dir, entries)
    out_path = session_dir / "session.md"

    if args.check:
        existing = out_path.read_text() if out_path.exists() else ""
        if existing != rendered:
            print(f"stale: {out_path} is out of date - run: tools/merge_sessions.py {session_dir}", file=sys.stderr)
            return 1
        print(f"ok: {out_path} is up to date ({len(entries)} entries)")
        return 0

    out_path.write_text(rendered)
    print(f"merged {len(entries)} entries from {len(list(session_dir.glob('session.*.md')))} files -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
