title: Deep Cuts
description: 100% offline studio audio analysis application and reference library.
baseurl: "/deep-cuts"
url: "https://robertolupi.github.io"

# File exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
